apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-a
  labels:
    dashboards: grafana-a
    folders: grafana-a
  namespace: ibm-ce-prometheus
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: start
      admin_user: root
  route:
    spec:
      to:
        weight: 100
        kind: Service
